### ISSUE TITLE
Collections 4.0.0-alpha : Old class_key CollectionContainer is not changed

### ISSUE THREAD

**Issue by Jako** [modxcms/Collections#336]
The old class_key CollectionContainer is not changed from `CollectionContainer` to `Collections\Model\CollectionContainer` during installing Collections 4 alpha. Collections 3 was not installed in this installation. Only the database was copied from MODX 2.x to MODX 3.x.

**Comment by Mark-H** [comment]
Just tried this on a site and it did not seem to run that migration. Had to fix it manually in the database.

I didn't keep installation logs unfortunately, but the first time I tried to install it failed with a fatal error because Collections was still being loaded from the `extension_packages`, which ran into a `require_once` call for modprocessor and bombed the upgrade.

After removing collections from the extension_packages, I could complete the installation. I'm guessing though that the resolver didn't run because it only runs on `xPDOTransport::ACTION_UPGRADE`, while after a failed installation it'll process as a `xPDOTransport::ACTION_INSTALL` because it doesn't appear as installed yet in the list of packages.

To get Collections to update properly in one go I think two tweaks will be needed:

- Before or immediately after replacing files, remove the extension package. 
- Add `xPDOTransport::ACTION_INSTALL` to the resolver so it'll still execute if it failed a first attempt
